AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating agent deploy instance"

Parameters:
  NetworkStack:
    Type: String
    Default: NetworkStack
  
  EfsStack:
    Type: String
    Default: EfsStack
  
  DeploymentGroupName:
    Type: String
    Default: test
  
  ProjectName:
    Type: String
    Default: BI ITIX
  
  RepoUrl:
    Type: String
    Default: git@ssh.dev.azure.com:v3/itixti/BI%20ITIX/TESTE

Resources:
  # - mkdir /home/ec2-user/efs/projeto
  # - sudo yum -y install git
  # - cd /home/ec2-user/efs/projeto
  # - git init
  # - git clone ${RepoUrl}

  AgentDeploy: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: 'us-east-1a'
      DisableApiTermination: false
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: t2.micro
      KeyName: agentDeploy
      IamInstanceProfile: AgenteDeployRole
      Monitoring: "true"
      SubnetId: 
        !ImportValue 
        'Fn::Sub': "${NetworkStack}-PrivateSubnetAID"
      SecurityGroupIds:
        - !ImportValue 
          'Fn::Sub': "${NetworkStack}-AgentDeploySGID"
      UserData: 
        Fn::Base64: 
          Fn::Sub: 
            - |
              #cloud-config
              runcmd:
              - sudo yum update
              - sudo yum -y install expect
              - sudo yum -y install nfs-utils
              - sudo yum -y install git
              - mkdir -p /home/ec2-user/azagent
              - curl -fkSL  https://vstsagentpackage.azureedge.net/agent/2.195.2/vsts-agent-linux-x64-2.195.2.tar.gz --output /home/ec2-user/azagent/vstsagent.tar.gz
              - tar -zxvf /home/ec2-user/azagent/vstsagent.tar.gz -C /home/ec2-user/azagent
              - sudo chown -R ec2-user:ec2-user /home/ec2-user/azagent
              - PAT=$(aws --region=${AWS::Region} ssm get-parameter --name "pat_token" --output text --query Parameter.Value)
              - cd /home/ec2-user/azagent
              - if [ -x "$(command -v systemctl)" ] 
              - then 
              - sudo -u ec2-user ./config.sh --deploymentgroup --deploymentgroupname '${DeploymentGroupName}' --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/itixti/ --work _work --projectname '${ProjectName}' --auth PAT --token $PAT --runasservice
              - sudo ./svc.sh install
              - sudo ./svc.sh start
              - else 
              - sudo -u ec2-user ./config.sh --deploymentgroup --deploymentgroupname '${DeploymentGroupName}' --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/itixti/ --work _work --projectname '${ProjectName}' --auth PAT --token $PAT
              - sudo -u ec2-user ./run.sh
              - fi
              - sudo mkdir -p /home/ec2-user/efs/
              - sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${EfsId}.efs.${AWS::Region}.amazonaws.com:/ /home/ec2-user/efs/
              - sudo echo "${EfsId}.efs.${AWS::Region}.amazonaws.com:/ /home/ec2-user/efs/ nfs defaults,_netdev 0 0" >> /etc/fstab 
              - SshKey=$(aws --region=${AWS::Region} ssm get-parameter --name "private_ssh" --output text --query Parameter.Value)
              - echo $SshKey > /home/ec2-user/.ssh/azure_ssh
              - chmod 400 /home/ec2-user/.ssh/azure_ssh
              - sudo chown ec2-user:ec2-user /home/ec2-user/.ssh/azure_ssh
              - eval `ssh-agent -s`
              - ssh-add -l
              - PassPhrase=$(aws --region=${AWS::Region} ssm get-parameter --name "passphrase" --output text --query Parameter.Value)
              - echo $PassPhrase > /home/ec2-user/passphrase
              - echo "#!/bin/expect -f" >> /home/ec2-user/run_ssh_add.sh
              - echo "set file [exec cat /home/ec2-user/passphrase]" >> /home/ec2-user/run_ssh_add.sh
              - echo "spawn ssh-add /home/ec2-user/.ssh/azure_ssh" >> /home/ec2-user/run_ssh_add.sh
              - echo 'expect "Enter passphrase for /home/ec2-user/.ssh/azure_ssh:"' >> /home/ec2-user/run_ssh_add.sh
              - echo 'send "$file\\n"' >> /home/ec2-user/run_ssh_add.sh
              - echo "interact" >> /home/ec2-user/run_ssh_add.sh
              - sudo chmod +x /home/ec2-user/run_ssh_add.sh
              - /home/ec2-user/run_ssh_add.sh
              - ssh-add -l
              - sudo chown -R ec2-user:ec2-user /home/ec2-user/
            - EfsId: 
                Fn::ImportValue: 
                  !Sub "${EfsStack}-ElasticFileSystemID"
                  

