AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating agent deploy instance"

Parameters:
  NetworkStack:
    Type: String
    Default: NetworkStack
  
  EfsStack:
    Type: String
    Default: EfsStack

Resources:
  
  AgentDeploy: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: 'us-east-1a'
      DisableApiTermination: false
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: t2.micro
      KeyName: agent_deploy
      IamInstanceProfile: AgenteDeployRole
      Monitoring: "true"
      SubnetId: 
        !ImportValue 
        'Fn::Sub': "${NetworkStack}-PrivateSubnetAID"
      SecurityGroupIds:
        - !ImportValue 
          'Fn::Sub': "${NetworkStack}-AgentDeploySGID"
      UserData: 
        Fn::Base64: 
          Fn::Sub: 
            - |
              #cloud-config
              runcmd:
              - sudo yum update
              - sudo yum -y install nfs-utils
              - sudo mkdir -p /mnt/efs/
              - sudo chown -R ec2-user:ec2-user /mnt/efs/
              - sudo mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${EfsId}.efs.${AWS::Region}.amazonaws.com:/ /mnt/efs/
              - sudo echo "${EfsId}.efs.${AWS::Region}.amazonaws.com:/ /mnt/efs/ nfs defaults,_netdev 0 0" >> /etc/fstab 
              - echo ${SshKey} > /home/ec2-user/.ssh/azure_ssh
              - eval $(ssh-agent)
              - ssh-add /home/ec2-user/.ssh/azure_ssh
            - EfsId: 
                Fn::ImportValue: 
                  !Sub "${EfsStack}-ElasticFileSystemID"
              SshKey: '{{resolve:ssm:private_ssh:1}}'
                  
