AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating network file system"

Parameters:
  NetworkStack:
    Type: String
    Default: NetworkStack

Resources:
  ElasticFileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      BackupPolicy: 
        Status: DISABLED
      Encrypted: false
      PerformanceMode: generalPurpose

  MountTargetA: 
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: 
        Ref: ElasticFileSystem
      SubnetId: !ImportValue
        'Fn::Sub': "${NetworkStack}-PrivateSubnetAID"
      SecurityGroups: 
        - !ImportValue 
          'Fn::Sub': "${NetworkStack}-NetworkFileSystemSGID"
          
  MountTargetB: 
    Type: AWS::EFS::MountTarget
    DependsOn: MountTargetA
    Properties: 
      FileSystemId: 
        Ref: ElasticFileSystem
      SubnetId: !ImportValue
        'Fn::Sub': "${NetworkStack}-PrivateSubnetBID"
      SecurityGroups: 
        - !ImportValue 
          'Fn::Sub': "${NetworkStack}-NetworkFileSystemSGID"

Outputs:
  outputElasticFileSystem:
    Description: Elastic File System ID
    Value: !Ref ElasticFileSystem
    Export:
      Name: !Sub "${AWS::StackName}-ElasticFileSystemID"

  outputMountTargetA:
    Description: EFS Mount Target A
    Value: !Ref MountTargetA
    Export:
      Name: !Sub "${AWS::StackName}-MountTargetAID"

  outputMountTargetB:
    Description: EFS Mount Target B
    Value: !Ref MountTargetB
    Export:
      Name: !Sub "${AWS::StackName}-MountTargetBID"