AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating IAM Roles"

Resources:
  AirflowInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Action: 'rds:*'
                Resource: '*'