AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating IAM Roles"

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Enable EC2 access to RDS instance
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 
              - 'rds:*'
            Resource: '*'